default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: password

development:
  <<: *default
  database: open_vagas_development

test:
  <<: *default
  database: open_vagas_test

production:
  <<: *default
  database: open_vagas_production
  username: open_vagas
  password: <%= ENV['OPEN_VAGAS_DATABASE_PASSWORD'] %>
